// AUTO-GENERATED by scripts/api-surface.mjs — DO NOT EDIT.
// Public type surface of @tag-kit/core. Regenerate with `pnpm api:generate`.

// ── dist/builder.d.ts ────────────────────────────────────────────────
/**
 * Ergonomic helpers for constructing catalog entries and combining catalogs.
 *
 * The verbose object-literal form remains supported (and is the canonical
 * shape after `.build()` returns). The builder exists to cut keystrokes
 * and surface sensible defaults for the boolean scope flags.
 */
import { type TagCatalogEntry } from "./catalog.js";
/**
 * Chainable builder for a single catalog entry.
 *
 *     const TAG = tag("audio.harassment")
 *       .name("Audio harassment")
 *       .desc("Spoken harassment, slurs, or threats.")
 *       .severity("danger")
 *       .group("Audio")
 *       .modalities("audio", "video")
 *       .segments()      // turn on segment scope
 *       .build();
 *
 * Defaults:
 *   - severity: "neutral"
 *   - group: "Default"
 *   - applicableModalities: [] (universal — applies to every modality)
 *   - supportsSegmentScope: false
 *   - supportsSpanScope: false
 *
 * Required (must be set before build):
 *   - tagId (passed to `tag()`)
 *   - displayName (`.name()`)
 *   - description (`.desc()`)
 *
 * `.build()` validates the entry by piping it through `defineCatalog`,
 * so missing required fields throw with the same error codes as the
 * passthrough form.
 */
export declare function tag<TTagId extends string = string>(tagId: TTagId): TagBuilder<TTagId>;
declare class TagBuilder<TTagId extends string> {
    private readonly _tagId;
    private _displayName;
    private _description;
    private _severity;
    private _group;
    private _applicableModalities;
    private _supportsSegmentScope;
    private _supportsSpanScope;
    constructor(tagId: TTagId);
    name(displayName: string): this;
    desc(description: string): this;
    severity(severity: TagCatalogEntry["severity"]): this;
    group(group: string): this;
    modalities<TModality extends string>(...modalities: TModality[]): this;
    /** Turn on segment-scope support (time-bounded annotations). */
    segments(enable?: boolean): this;
    /** Turn on span-scope support (offset-bounded annotations). */
    spans(enable?: boolean): this;
    /**
     * Materialize the entry. Throws if any required field is missing — the
     * same validation that `defineCatalog` applies, so a builder-produced
     * entry will always pass `defineCatalog([entry])`.
     */
    build(): TagCatalogEntry & {
        tagId: TTagId;
    };
}
/**
 * Combine multiple catalogs into one. Validates the result so duplicate
 * `tagId`s across catalogs surface as `DUPLICATE_TAG_ID` at merge time
 * (rather than later, deeper in scoring).
 *
 *     const FULL = mergeCatalogs(TEXT_CATALOG, IMAGE_CATALOG, VIDEO_CATALOG);
 *
 * Returns a new readonly array; inputs are not mutated. The returned
 * array preserves the input order: catalog A's entries come first, then
 * catalog B's, etc.
 */
export declare function mergeCatalogs<T extends TagCatalogEntry>(...catalogs: readonly (readonly T[])[]): readonly T[];
/**
 * Type-safe namespacing helper. Constrains every entry's `tagId` to the
 * `<modality>.<rest>` pattern at compile time, where `<modality>` must
 * be one of the supplied `modalities` tuple.
 *
 *     const C = defineNamespacedCatalog(["text", "image"] as const, [
 *       tag("text.toxic").name(...).desc(...).build(),
 *       tag("image.nsfw").name(...).desc(...).build(),
 *       tag("audio.bad").name(...).desc(...).build(),  // ❌ TS error
 *     ]);
 *
 * Pure type-level narrowing — runtime behavior is identical to
 * `defineCatalog`. Falls back to plain `defineCatalog` if you need
 * tagIds that don't follow the convention.
 */
export declare function defineNamespacedCatalog<const TModalities extends readonly string[], TEntries extends readonly NamespacedEntry<TModalities[number]>[]>(_modalities: TModalities, entries: TEntries): TEntries;
/**
 * Catalog entry whose `tagId` is constrained to `${TModality}.${string}`.
 * Used by `defineNamespacedCatalog` to narrow the literal type.
 */
export type NamespacedEntry<TModality extends string> = TagCatalogEntry & {
    tagId: `${TModality}.${string}`;
};
export {};

// ── dist/catalog.d.ts ────────────────────────────────────────────────
/**
 * Tag catalog — the *index* of annotation vocabulary your domain offers.
 *
 * `tag-kit` doesn't ship a catalog. Each consumer defines their own with
 * `defineCatalog([...])` — content moderation will register `text.tone-violation`
 * and `audio.harassment`; medical chart annotation will register
 * `diagnosis.suggested` and `medication.contraindicated`. The catalog is the
 * stable contract; entries are referenced by `tagId` from
 * `ReviewerTag` / `ExpectedTag` rows.
 *
 * Naming convention recommendation: `<modality>.<category>` keeps catalogs
 * scannable, but `tag-kit` doesn't enforce it.
 */
/**
 * One entry in a TagCatalog. Generic over modality + group so consumers can
 * narrow the types in their domain (e.g.
 * `TagCatalogEntry<"text" | "image" | "video", "Toxicity" | "Privacy">`).
 */
export interface TagCatalogEntry<TModality extends string = string, TGroup extends string = string> {
    /** Stable identifier — FK from `ReviewerTag.tagId`. Never change once shipped. */
    tagId: string;
    /** Display label. Free to evolve. */
    displayName: string;
    /** One-liner shown in the picker tooltip and the chip hover. */
    description: string;
    /** Modalities the dashboard surfaces this tag for. Empty array = always shown. */
    applicableModalities: readonly TModality[];
    /** Visual tone for chips + sort priority for the picker. */
    severity: "info" | "warn" | "danger" | "neutral";
    /** Optional grouping for the picker (e.g. "Toxicity", "Privacy"). */
    group: TGroup;
    /** True iff the tag may be applied with a time-bounded scope. */
    supportsSegmentScope: boolean;
    /** True iff the tag may be applied with an offset-bounded scope. */
    supportsSpanScope: boolean;
}
/** Built-in validation rule codes. Custom rules may use any string code. */
export type BuiltInCatalogValidationCode = "EMPTY_TAG_ID" | "DUPLICATE_TAG_ID" | "INVALID_TAG_ID_CHARS" | "EMPTY_DISPLAY_NAME" | "EMPTY_DESCRIPTION" | "EMPTY_GROUP";
/** Open string union so custom rules can ship their own codes. */
export type CatalogValidationCode = BuiltInCatalogValidationCode | (string & {});
/** One validation finding. `severity: "error"` blocks `defineCatalog` in
 *  strict mode; `"warn"` is informational and never throws. */
export interface CatalogValidationError {
    index: number;
    tagId?: string;
    code: CatalogValidationCode;
    severity: "error" | "warn";
    message: string;
}
/**
 * A consumer-supplied validation rule. Returns:
 *   - `null` if the entry passes
 *   - a `string` to fail with that message (uses the rule's default severity)
 *   - an object `{ message, severity }` to fail with explicit severity
 */
export interface CustomCatalogRule<T extends TagCatalogEntry = TagCatalogEntry> {
    /** Stable identifier for this rule. Surfaces in error messages. */
    code: string;
    /** Default severity if `validate` returns a bare string. Defaults to `"error"`. */
    severity?: "error" | "warn";
    validate: (entry: T, index: number, all: readonly T[]) => string | {
        message: string;
        severity?: "error" | "warn";
    } | null;
}
/** Options accepted by `defineCatalog` and `validateCatalog`. */
export interface DefineCatalogOptions<T extends TagCatalogEntry = TagCatalogEntry> {
    /** Additional rules applied after the built-ins. */
    rules?: readonly CustomCatalogRule<T>[];
    /**
     * "strict" (default) — throw on any error-severity finding.
     * "warn"            — never throw; emit console.warn for each finding.
     */
    severity?: "strict" | "warn";
}
/** Aggregated validation result returned by `validateCatalog`. */
export interface ValidateCatalogResult {
    /** True iff there are no `error`-severity findings (warnings are tolerated). */
    ok: boolean;
    errors: readonly CatalogValidationError[];
    warnings: readonly CatalogValidationError[];
    /** All findings (errors ∪ warnings) in their original order. */
    all: readonly CatalogValidationError[];
}
/**
 * Helper that returns its argument typed as a readonly catalog. Validates
 * entries at the boot-time call site.
 *
 *     const CATALOG = defineCatalog([...]);
 *
 *     // With custom rules:
 *     defineCatalog(entries, {
 *       rules: [{
 *         code: "TAG_ID_PREFIX",
 *         validate: (e) => e.tagId.startsWith("text.") ? null : "must start with text.",
 *       }],
 *     });
 *
 *     // Tolerant mode — never throws, emits console.warn:
 *     defineCatalog(entries, { severity: "warn" });
 *
 * Default behavior unchanged from 0.2.x: built-in rules run, errors throw.
 */
export declare function defineCatalog<TEntry extends TagCatalogEntry>(entries: readonly TEntry[], options?: DefineCatalogOptions<TEntry>): readonly TEntry[];
/**
 * Validate a catalog without throwing. Returns the result as data so
 * consumers loading catalogs from config files (YAML, JSON, etc.) can
 * surface errors to the user instead of crashing the app.
 *
 *     const result = validateCatalog(entries);
 *     if (!result.ok) {
 *       for (const err of result.errors) console.error(err);
 *     }
 */
export declare function validateCatalog<TEntry extends TagCatalogEntry>(entries: readonly TEntry[], options?: {
    rules?: readonly CustomCatalogRule<TEntry>[];
}): ValidateCatalogResult;
/** Lookup by tagId. Returns undefined for unknown ids. O(n) — catalogs are small. */
export declare function findEntry<T extends TagCatalogEntry>(catalog: readonly T[], tagId: string): T | undefined;
/**
 * Filter the catalog by modality — the picker uses this to surface only
 * relevant tags for the asset under review. An entry with empty
 * `applicableModalities` matches every modality (a "universal" tag).
 */
export declare function filterByModality<T extends TagCatalogEntry>(catalog: readonly T[], modality: string): T[];
/** Bucket the catalog into `{ groupName: entries[] }` for the picker. */
export declare function groupByCategory<T extends TagCatalogEntry>(catalog: readonly T[]): Record<string, T[]>;

// ── dist/index.d.ts ──────────────────────────────────────────────────
/**
 * @tag-kit/core — domain-agnostic tagging primitives for HITL workflows.
 *
 * Three concerns, three modules:
 *  - schema.ts    — wire shapes (TagScope, ReviewerTag, ExpectedTag, TagAgreement)
 *  - catalog.ts   — domain-defined vocabulary index + filter helpers
 *  - matching.ts  — scope-overlap rules for "did annotator A and B agree?"
 *  - scoring.ts   — per-tag precision / recall / F1 across many entities
 *
 * Bring your own catalog. Bring your own UI (or use `@tag-kit/ui`).
 * The scoring math is pure, the matching is conservative, and the schema
 * generalizes across audio, video, text, document, and code annotation.
 */
export * from "./schema.js";
export * from "./catalog.js";
export * from "./builder.js";
export * from "./matching.js";
export * from "./strategies.js";
export * from "./scoring.js";

// ── dist/matching.d.ts ───────────────────────────────────────────────
import type { TagScope } from "./schema.js";
/**
 * Scope-overlap rules — when does annotator A's tag count as agreeing with
 * annotator B's tag of the same `tagId`?
 *
 * The conservative interpretation: scopes overlap when they could plausibly
 * refer to the same evidence. This means:
 *
 *  - Both undefined → match (both annotators tagged the whole entity).
 *  - Different `modality` → no match (text-tag ≠ audio-tag).
 *  - Different `assetId` → no match (different child asset).
 *  - Same modality + same assetId + segment ranges intersect → match.
 *  - Same modality + same assetId + span ranges intersect → match.
 *  - One has a fine-grained scope (segment / span / assetId) and the other is
 *    broader (whole-modality, or no scope) → match. The broader scope
 *    contains the narrower one, so they're talking about the same evidence.
 *
 * `tag-kit` deliberately doesn't try to interpret unknown fields — if your
 * domain needs custom geometry (polygon ROI, multi-region selection), wrap
 * `scopeOverlaps` and add the extra check at the domain layer.
 */
export declare function scopeOverlaps(a: TagScope | undefined | null, b: TagScope | undefined | null): boolean;
/** Two tags match if they share a tagId AND their scopes overlap per
 *  `scopeOverlaps`. Used in agreement scoring to decide TP / FP / FN. */
export declare function tagsMatch(a: {
    tagId: string;
    scope?: TagScope;
}, b: {
    tagId: string;
    scope?: TagScope;
}): boolean;

// ── dist/schema.d.ts ─────────────────────────────────────────────────
/**
 * Wire shapes for tags + expectations + agreement scores.
 *
 * Domain-agnostic by design — `modality` is a free string defined by the
 * consumer's catalog (e.g. "text" / "image" / "video.audio-track" /
 * "document.page-3"). `assetId` references whatever child entity the
 * consumer's domain attaches to a parent (a media asset, a paragraph,
 * a transcript turn).
 *
 * Two scope shapes cover most annotation work:
 *   - `segment` for time-bounded scopes (audio second 12-24, video frame range)
 *   - `span`    for offset-bounded scopes (character offsets, byte offsets,
 *               token positions)
 *
 * Anything beyond these — custom geometry, multi-region selection — should
 * compose at the consumer layer rather than expand the core schema.
 */
/**
 * Where on the annotated entity a tag applies. When all fields are absent,
 * the tag applies to the whole entity.
 *
 * The semantics of `segment.start/end` and `span.start/end` are defined by
 * the consumer (seconds vs. frames vs. samples; characters vs. bytes vs.
 * tokens). `tag-kit` doesn't enforce a unit so the same primitives work
 * across audio, video, text, document, and code annotation.
 */
export interface TagScope {
    modality?: string;
    assetId?: string;
    segment?: {
        start: number;
        end: number;
    };
    span?: {
        start: number;
        end: number;
    };
}
/**
 * One tag a reviewer (or any annotator) applied. Multiple tags per
 * decision is normal — the same artefact can carry several scoped
 * annotations.
 */
export interface ReviewerTag {
    /** Stable identifier from the consumer's catalog. */
    tagId: string;
    scope?: TagScope;
    /** Free-form annotator note — additional context the catalog tag can't
     *  capture. Surfaced in the dashboard chip's tooltip. */
    note?: string;
}
/**
 * A tag the consumer's gold-set says SHOULD have been applied. Pairs with
 * `ReviewerTag` for binary precision/recall agreement scoring.
 */
export interface ExpectedTag {
    tagId: string;
    scope?: TagScope;
    /** Labeler confidence. Consumers may use this to weight aggregates. */
    confidence?: "high" | "medium" | "low";
}
/**
 * Aggregated precision / recall / F1 for one tag across many annotated
 * entities. Returned by `tagPrecisionRecall` from `./scoring`.
 *
 * NaN is replaced with 0 throughout so the shape serializes cleanly even
 * when there are no positives.
 */
export interface TagAgreement {
    tagId: string;
    /** TP: expected ∧ predicted with overlapping scope. */
    truePositives: number;
    /** FP: predicted ∧ ¬expected. */
    falsePositives: number;
    /** FN: expected ∧ ¬predicted. */
    falseNegatives: number;
    /** TP / (TP + FP). 0 when no positives. */
    precision: number;
    /** TP / (TP + FN). 0 when no positives. */
    recall: number;
    /** Harmonic mean of precision + recall. 0 when both are 0. */
    f1: number;
    /** TP + FP + FN. The "interesting" sample count — entities where this tag
     *  was either expected or predicted. Pure true-negatives are excluded. */
    samples: number;
}

// ── dist/scoring.d.ts ────────────────────────────────────────────────
import type { ExpectedTag, ReviewerTag, TagAgreement } from "./schema.js";
import { type MatchStrategy } from "./strategies.js";
/**
 * Agreement scoring — precision / recall / F1 per tag, aggregated across
 * many entities.
 *
 * Tag scoring is binary, not probabilistic. For each entity in the dataset:
 *   - true positive : expected ∧ predicted (matching scopes via tagsMatch)
 *   - false positive: predicted ∧ ¬expected
 *   - false negative: expected ∧ ¬predicted
 *
 * `samples` counts only "interesting" entities — pure true-negatives
 * (entity has no expected and no predicted tag of this id) don't contribute,
 * because they'd dominate the count and make the metric meaningless.
 *
 * NaN is replaced with 0 throughout so the wire shape serializes cleanly.
 */
export interface TaggedEntity {
    /** Stable id for the entity being scored — only used to keep callers'
     *  expected and predicted aligned. Never inspected by the scorer. */
    entityId: string;
    expected: readonly ExpectedTag[];
    predicted: readonly ReviewerTag[];
}
/**
 * Compute per-tag agreement across many entities. Returns one
 * `TagAgreement` row per `tagId` that appeared in either the expected or
 * predicted set on any entity.
 *
 * The optional `strategy` parameter swaps in alternative matching rules
 * (e.g. `looseMatch`, `fuzzyMatch({ distance: 1 })`, `confidentMatch({...})`).
 * Defaults to `strictMatch` — the conservative scope-overlap rules that
 * shipped in 0.1.x. With `strategy` omitted, output is byte-for-byte
 * identical to pre-strategy releases.
 *
 * Important — `fuzzyMatch` uses `tagId` similarity to decide matches,
 * but the returned `TagAgreement` is still keyed by the *predicted*
 * `tagId`. Aggregation is alphabetical by tagId so dashboards render
 * consistently across runs.
 */
export declare function tagPrecisionRecall(entities: readonly TaggedEntity[], strategy?: MatchStrategy): TagAgreement[];
/** Lightweight aggregator for one tag at a time — useful when callers
 *  pre-bucketed by tagId. Same scoring rules as `tagPrecisionRecall`. */
export interface BinarySample {
    expected: boolean;
    predicted: boolean;
}
export declare function binaryAgreement(tagId: string, samples: readonly BinarySample[]): TagAgreement;

// ── dist/strategies.d.ts ─────────────────────────────────────────────
/**
 * Pluggable matching strategies — alternative rules for "did annotator A
 * and B agree?" beyond the conservative default in `matching.ts`.
 *
 * The default `tagsMatch` (and therefore `tagPrecisionRecall`) uses
 * `strictMatch`, which is what shipped in 0.1.x. Other strategies are
 * opt-in: callers pass them as the optional final argument.
 *
 * Strategies are pure: they take two tag-like values and return a boolean.
 * That makes them composable — wrap one in another, or chain via
 * `combineStrategies(...)`.
 */
import type { ExpectedTag, ReviewerTag, TagScope } from "./schema.js";
/** A tag with the minimum fields a strategy can rely on. */
export interface MatchableTag {
    tagId: string;
    scope?: TagScope;
    /** Optional confidence — only `ExpectedTag` carries this; predicted tags
     *  may be cast to MatchableTag with confidence undefined. Matches the
     *  three-level enum used by `ExpectedTag.confidence`. */
    confidence?: "high" | "medium" | "low";
}
declare const CONFIDENCE_ORDER: {
    readonly low: 1;
    readonly medium: 2;
    readonly high: 3;
};
type ConfidenceLevel = keyof typeof CONFIDENCE_ORDER;
/**
 * A strategy is just a boolean predicate over two tags. Library-built
 * strategies are objects with a `match` function so they can carry
 * configuration (e.g. fuzzy distance) in their closure.
 */
export interface MatchStrategy {
    /** Friendly name surfaced in errors / logs. */
    readonly name: string;
    match(a: MatchableTag, b: MatchableTag): boolean;
}
/**
 * Conservative match — `tagId` equality + scope overlap with half-open
 * intervals. This is what `tagsMatch` uses by default.
 */
export declare const strictMatch: MatchStrategy;
/**
 * Loose match — like `strict`, but ranges that touch at the boundary
 * count as overlapping. Use when the consumer's `start`/`end` values
 * are inclusive (e.g. frame indices that semantically include their endpoint).
 *
 * Example: `[10, 20]` and `[20, 30]` → `loose` says match, `strict` does not.
 */
export declare const looseMatch: MatchStrategy;
/**
 * Fuzzy match — tolerate typos in `tagId` up to a Levenshtein distance.
 * Scope rules are identical to `strict`.
 *
 *     fuzzyMatch({ distance: 2 })  // tolerate up to 2 single-char edits
 *
 * Distance defaults to `1` (a single typo). At distance 0, behavior is
 * equivalent to `strictMatch`.
 *
 * Hand-rolled Levenshtein — no external deps. O(m*n) per comparison,
 * which is fine for short tagIds (typical: 10–30 chars).
 */
export declare function fuzzyMatch(opts?: {
    distance?: number;
}): MatchStrategy;
/**
 * Confidence-gated match — pure filter that returns true iff both tags
 * meet `minConfidence`. Does NOT check `tagId` or `scope` — compose with
 * `strictMatch` / `looseMatch` / `fuzzyMatch` via `combineStrategies` to
 * stack a confidence gate on top of tag-identity rules.
 *
 *     // Strict tagId+scope AND confidence ≥ medium:
 *     combineStrategies(strictMatch, confidentMatch({ minConfidence: "medium" }))
 *
 *     // Fuzzy tagId AND confidence ≥ high:
 *     combineStrategies(fuzzyMatch({ distance: 1 }), confidentMatch({ minConfidence: "high" }))
 *
 * Tags without a `confidence` field are treated as fully confident
 * ("high") — only `ExpectedTag` carries this field; `ReviewerTag` sources
 * typically don't.
 *
 * Confidence ordering: `low < medium < high`.
 */
export declare function confidentMatch(opts: {
    minConfidence: ConfidenceLevel;
}): MatchStrategy;
/**
 * Combine multiple strategies — match if ALL strategies agree. Useful for
 * stacking constraints (e.g. fuzzy + confident).
 */
export declare function combineStrategies(...strategies: readonly MatchStrategy[]): MatchStrategy;
/**
 * Match two tags using the supplied strategy. Equivalent to calling
 * `strategy.match(a, b)` directly — provided for readability at call sites.
 */
export declare function tagsMatchWith(a: ReviewerTag | ExpectedTag, b: ReviewerTag | ExpectedTag, strategy?: MatchStrategy): boolean;
export {};

