// AUTO-GENERATED by scripts/api-surface.mjs — DO NOT EDIT.
// Public type surface of @tag-kit/ui. Regenerate with `pnpm api:generate`.

// ── dist/TagChip.d.ts ────────────────────────────────────────────────
import type { ReactNode } from "react";
import type { ReviewerTag, TagCatalogEntry } from "@tag-kit/core";
export interface TagChipProps {
    /** The tag to render. */
    tag: ReviewerTag;
    /** Catalog entry for the tag's `tagId`. When undefined, falls back to
     *  rendering the raw `tagId` — useful when the catalog is loading. */
    entry?: TagCatalogEntry;
    /** Optional state hint — `saved` tags came from persistence; `staged`
     *  tags are pending commit. Surfaces in the chip's data attribute. */
    state?: "saved" | "staged";
    /** When provided, the chip renders a remove button that fires this
     *  callback. Omit to render a read-only chip. */
    onRemove?: () => void;
    /** Replace the default markup. Useful when you want to render the chip
     *  inside your design-system primitives. */
    children?: (info: TagChipRenderInfo) => ReactNode;
}
export interface TagChipRenderInfo {
    label: string;
    severity: TagCatalogEntry["severity"] | "neutral";
    state: "saved" | "staged" | undefined;
    note: string | undefined;
    onRemove: (() => void) | undefined;
    /** Tooltip-friendly long form: `tagId — note`. */
    title: string;
}
/**
 * Headless tag chip. Renders zero styles by default — emits semantic
 * `data-tag-kit-*` attributes the consumer styles with their own CSS.
 *
 * Pass a `children` render-prop to take full control over the markup
 * (drop the chip into your design-system Badge / Tag primitive).
 */
export declare function TagChip({ tag, entry, state, onRemove, children }: TagChipProps): import("react/jsx-runtime").JSX.Element;

// ── dist/TagFilter.d.ts ──────────────────────────────────────────────
import { type ReactNode } from "react";
import type { TagCatalogEntry } from "@tag-kit/core";
export interface TagFilterValue {
    /** Active severity allowlist. Empty = all severities. */
    severity?: readonly TagCatalogEntry["severity"][];
    /** Active group allowlist. Empty = all groups. */
    group?: readonly string[];
    /** Active modality allowlist. Empty = all modalities. */
    modality?: readonly string[];
}
export type TagFilterFacet = "severity" | "group" | "modality";
export interface TagFilterFacetOption {
    facet: TagFilterFacet;
    /** The bucket value (e.g. "danger", "Toxicity", "audio"). */
    value: string;
    /** True iff this option is currently in the active allowlist. */
    active: boolean;
    /** Number of catalog entries that fall under this option (helps the
     *  consumer's UI show counts next to checkboxes). */
    count: number;
    /** Toggle this option on/off and emit a new TagFilterValue. */
    toggle: () => void;
}
export interface TagFilterRenderInfo {
    options: readonly TagFilterFacetOption[];
    /** Convenience: clear every facet to "show all". */
    clear: () => void;
    value: TagFilterValue;
}
export interface TagFilterProps {
    /** Catalog whose facet values populate the filter options. */
    catalog: readonly TagCatalogEntry[];
    /** Current filter state (controlled). */
    value: TagFilterValue;
    /** Fired when the user toggles an option. */
    onChange: (next: TagFilterValue) => void;
    /** Which facets to surface. Defaults to all three. */
    facets?: readonly TagFilterFacet[];
    /** Replace the default markup. */
    children?: (info: TagFilterRenderInfo) => ReactNode;
}
/**
 * Headless toggle-style filter UI. Surfaces the unique severity / group /
 * modality values from the catalog and lets the user toggle them on/off.
 * Renders zero styles by default — `data-tag-kit-*` attributes are the
 * styling hook.
 *
 *     const [filter, setFilter] = useState<TagFilterValue>({});
 *     <TagFilter catalog={CATALOG} value={filter} onChange={setFilter} />
 *
 * Pair with `useTagFilter(staged, filter, catalog)` to filter the
 * displayed tag list.
 */
export declare function TagFilter({ catalog, value, onChange, facets, children, }: TagFilterProps): import("react/jsx-runtime").JSX.Element;

// ── dist/TagPicker.d.ts ──────────────────────────────────────────────
import { type ReactNode } from "react";
import { type ReviewerTag, type TagCatalogEntry } from "@tag-kit/core";
export interface TagPickerProps {
    /** The catalog to browse. Filtered by modality before display. */
    catalog: readonly TagCatalogEntry[];
    /** Currently-staged tags — entries already chosen are disabled in the picker. */
    staged: readonly {
        tagId: string;
    }[];
    /** Modality the picker should narrow to. Pass null to show every tag. */
    modality: string | null;
    /** Fired when the user picks a tag from the catalog. */
    onPick: (tag: ReviewerTag) => void;
    /** Optional initial query — useful for tests + deep-linking. */
    initialQuery?: string;
    /** Opt-in arrow-key navigation. When true:
     *   - ArrowDown / ArrowUp move the highlight through the visible list
     *     (skipping disabled entries).
     *   - Enter fires `onPick` for the highlighted entry.
     *   - Escape clears the search query.
     *  Off by default to keep the headless component truly opinion-free. */
    keyboard?: boolean;
    /** Render slot — wrap the picker content in your own popover / sheet / modal.
     *  Defaults to a plain `<div>` so the picker works headless. */
    children?: (content: ReactNode) => ReactNode;
}
/**
 * Headless tag picker. Filters the catalog by modality + free-text query,
 * groups by `entry.group`, and fires `onPick` when an entry is selected.
 *
 * The component renders zero styles by default — wrap it in your own
 * popover / sheet / dropdown and style the markup with whatever your app
 * uses (Tailwind, CSS modules, vanilla CSS). The data shape is what's
 * stable; the markup is intentionally generic.
 *
 * Pass `keyboard` to opt into arrow-key + Enter + Escape navigation. The
 * highlighted entry is exposed via `data-tag-kit-highlighted="true"` for
 * styling.
 */
export declare function TagPicker({ catalog, staged, modality, onPick, initialQuery, keyboard, children, }: TagPickerProps): import("react/jsx-runtime").JSX.Element;

// ── dist/TagSummary.d.ts ─────────────────────────────────────────────
import { type ReactNode } from "react";
import type { ReviewerTag, TagCatalogEntry } from "@tag-kit/core";
export type TagSummaryGroupBy = "tagId" | "modality" | "severity" | "group";
export interface TagSummaryEntry {
    /** The bucket key — e.g. `"text"` when `groupBy: "modality"`. */
    key: string;
    /** Number of tags in this bucket. */
    count: number;
    /** The tags in this bucket, preserving input order. */
    tags: readonly ReviewerTag[];
}
export interface TagSummaryRenderInfo {
    buckets: readonly TagSummaryEntry[];
    total: number;
}
export interface TagSummaryProps {
    /** Tags to summarize. */
    tags: readonly ReviewerTag[];
    /** Optional catalog used to resolve `severity` / `group` / `modality`
     *  for tags whose grouping isn't `tagId`. Without it, those groupings
     *  bucket every tag under `"unknown"`. */
    catalog?: readonly TagCatalogEntry[];
    /** What to bucket by. Defaults to `"tagId"`. */
    groupBy?: TagSummaryGroupBy;
    /** Replace the default markup with your own — receives the bucketed
     *  summary plus the total. Render-prop pattern matches TagPicker / TagChip. */
    children?: (info: TagSummaryRenderInfo) => ReactNode;
}
/**
 * Headless summary of a tag set — counts per `tagId`, `modality`,
 * `severity`, or `group`. Renders zero styles by default; emits
 * `data-tag-kit-*` attributes the consumer styles. Pass `children` to
 * take full control over the markup.
 *
 *     <TagSummary tags={staged} catalog={CATALOG} groupBy="severity" />
 *     // → <ul data-tag-kit="summary">
 *     //     <li data-tag-kit="summary-bucket" data-key="danger">danger: 3</li>
 *     //     ...
 *     //   </ul>
 */
export declare function TagSummary({ tags, catalog, groupBy, children }: TagSummaryProps): import("react/jsx-runtime").JSX.Element;

// ── dist/index.d.ts ──────────────────────────────────────────────────
/**
 * @tag-kit/ui — headless React components and hooks for tagging workflows.
 *
 * Components:
 *   - <TagPicker />  : catalog browser with modality filter + search,
 *                      grouped by entry.group, fires onPick. Optional
 *                      arrow-key navigation via `keyboard` prop.
 *   - <TagChip />    : display + optional remove button for one tag.
 *   - <TagSummary /> : counts per tagId / modality / severity / group.
 *   - <TagFilter />  : toggle-style filter UI driven by catalog facets.
 *
 * Hooks:
 *   - useTagStaging  : manages staged-tag React state with stage/unstage/has.
 *   - useTagFilter   : pure filter helper for ReviewerTag arrays.
 *
 * All components render zero styles by default — they emit semantic
 * `data-tag-kit-*` attributes the consumer styles with their own CSS.
 * Pass a `children` render-prop to take full control over the markup
 * (drop into shadcn / Mantine / your own design system).
 *
 * Domain types come from `@tag-kit/core` — re-exported here for
 * convenience so consumers can import everything from one place.
 */
export { TagPicker, type TagPickerProps } from "./TagPicker.js";
export { TagChip, type TagChipProps, type TagChipRenderInfo } from "./TagChip.js";
export { TagSummary, type TagSummaryProps, type TagSummaryGroupBy, type TagSummaryEntry, type TagSummaryRenderInfo, } from "./TagSummary.js";
export { TagFilter, type TagFilterProps, type TagFilterValue, type TagFilterFacet, type TagFilterFacetOption, type TagFilterRenderInfo, } from "./TagFilter.js";
export { useTagStaging, type UseTagStagingOptions, type UseTagStagingReturn, } from "./useTagStaging.js";
export { useTagFilter, type UseTagFilterOptions } from "./useTagFilter.js";
export type { ReviewerTag, ExpectedTag, TagAgreement, TagScope, TagCatalogEntry, } from "@tag-kit/core";

// ── dist/useTagFilter.d.ts ───────────────────────────────────────────
import { type ReviewerTag, type TagCatalogEntry } from "@tag-kit/core";
export interface UseTagFilterOptions {
    /** Restrict to tags whose catalog entry has this modality (or empty
     *  applicableModalities). Pass null/undefined to skip the modality
     *  filter. */
    modality?: string | null;
    /** Restrict to tags whose catalog entry severity is in this allowlist.
     *  Empty array or undefined skips the severity filter. */
    severity?: readonly TagCatalogEntry["severity"][];
    /** Restrict to tags whose catalog entry group is in this allowlist.
     *  Empty array or undefined skips the group filter. */
    group?: readonly string[];
    /** Free-text query — matched (case-insensitively, substring) against
     *  `tagId`, the catalog entry's `displayName`, and `description`. */
    query?: string;
}
/**
 * Filter a list of `ReviewerTag`s through any combination of modality,
 * severity, group, and free-text query — using the supplied catalog as
 * the source of truth for severity / group / displayName / description.
 *
 * Tags whose `tagId` is not in the catalog are kept (you may be rendering
 * a chip for an unknown tagId during catalog-loading) — they only match
 * the `query` filter against their own `tagId`.
 *
 *     const visible = useTagFilter(staged, {
 *       modality: "text",
 *       severity: ["danger", "warn"],
 *       query: search,
 *     });
 */
export declare function useTagFilter(tags: readonly ReviewerTag[], options: UseTagFilterOptions, catalog?: readonly TagCatalogEntry[]): readonly ReviewerTag[];

// ── dist/useTagStaging.d.ts ──────────────────────────────────────────
import type { ReviewerTag } from "@tag-kit/core";
export interface UseTagStagingOptions {
    /** Initial set of staged tags. Used only on first render — subsequent
     *  changes flow through the returned `stage` / `unstage` / `clear`. */
    initial?: readonly ReviewerTag[];
    /** Optional callback fired on every change (useful for persistence /
     *  controlled-form patterns). Receives the new staged array. */
    onChange?: (next: readonly ReviewerTag[]) => void;
}
export interface UseTagStagingReturn {
    staged: readonly ReviewerTag[];
    /** Add a tag. No-op if a tag with the same `tagId` is already staged
     *  (matches the TagPicker's "disable already-staged" semantics). */
    stage: (tag: ReviewerTag) => void;
    /** Remove the staged tag with the matching `tagId`. */
    unstage: (tagId: string) => void;
    /** Replace the staged set wholesale. */
    setStaged: (next: readonly ReviewerTag[]) => void;
    /** Remove every staged tag. */
    clear: () => void;
    /** True iff a tag with this `tagId` is currently staged. */
    has: (tagId: string) => boolean;
}
/**
 * Manages the staged-tag state most consumers roll themselves around
 * `<TagPicker />`. Pairs with `staged={staged}` and
 * `onPick={stage}`/`onRemove={() => unstage(tag.tagId)}`.
 *
 *     const { staged, stage, unstage, has, clear } = useTagStaging();
 *     return (
 *       <>
 *         <TagPicker catalog={C} staged={staged} modality="text" onPick={stage} />
 *         {staged.map((t) => (
 *           <TagChip
 *             key={t.tagId}
 *             tag={t}
 *             entry={C.find((e) => e.tagId === t.tagId)}
 *             onRemove={() => unstage(t.tagId)}
 *           />
 *         ))}
 *       </>
 *     );
 */
export declare function useTagStaging(options?: UseTagStagingOptions): UseTagStagingReturn;

