#!/usr/bin/env node
// @ts-check
/**
 * API SURFACE SNAPSHOT (`pnpm api:generate` / `pnpm api:check`)
 * ------------------------------------------------------------
 * Purpose: the committed public *type* surface of each published package changes
 * only on purpose. This is the drift gate that complements the runtime-export-name
 * Vitest snapshots (packages/<pkg>/test/api-surface.test.ts).
 *
 * How it works:
 *   1. Build all packages (`pnpm -r build`) so dist/*.d.ts is fresh.
 *   2. For each package, concatenate every emitted `.d.ts` file under dist/
 *      (sorted by path, sourcemap comments stripped, trailing WS normalised)
 *      into `api-surface/<pkg>.d.ts`.
 *   3. `--check` then runs `git diff --exit-code` on api-surface/; any change to
 *      a public declaration (a new export, a changed signature, a widened type)
 *      shows up as a diff and fails CI. Regenerate with `pnpm api:generate` and
 *      commit the diff when the change is intentional.
 *
 * Why concatenate dist/*.d.ts rather than roll up with api-extractor: the
 * published packages must ship zero new deps and the scripts are Node-only.
 * Concatenating the actual emitted declarations is dependency-free and faithful
 * to exactly what npm consumers receive in the tarball.
 *
 * Usage:
 *   node scripts/api-surface.mjs --write   (regenerate committed surface)
 *   node scripts/api-surface.mjs --check   (regenerate + fail on git diff)
 */
import { spawnSync } from "node:child_process";
import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..");

const PACKAGES = [
  { name: "core", dist: join(ROOT, "packages/core/dist") },
  { name: "ui", dist: join(ROOT, "packages/ui/dist") },
];

const mode = process.argv.includes("--check") ? "check" : "write";

function run(cmd, args, opts = {}) {
  const r = spawnSync(cmd, args, { stdio: "inherit", cwd: ROOT, ...opts });
  if (r.status !== 0) {
    console.error(`\n[api-surface] \`${cmd} ${args.join(" ")}\` failed (exit ${r.status}).`);
    process.exit(r.status ?? 1);
  }
  return r;
}

/** Collect every .d.ts (not .d.ts.map) under a dir, recursively, sorted. */
function collectDts(dir) {
  /** @type {string[]} */
  const out = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...collectDts(full));
    else if (entry.name.endsWith(".d.ts")) out.push(full);
  }
  return out.sort();
}

function normalise(src) {
  return src
    .split("\n")
    .filter((line) => !line.includes("//# sourceMappingURL="))
    .map((line) => line.replace(/\s+$/, ""))
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

console.log("[api-surface] building packages…");
run("pnpm", ["-r", "build"]);

for (const pkg of PACKAGES) {
  if (!existsSync(pkg.dist)) {
    console.error(`[api-surface] missing dist for ${pkg.name} at ${pkg.dist}`);
    process.exit(1);
  }
  const files = collectDts(pkg.dist);
  const header = `// AUTO-GENERATED by scripts/api-surface.mjs — DO NOT EDIT.\n// Public type surface of @tag-kit/${pkg.name}. Regenerate with \`pnpm api:generate\`.\n`;
  const body = files
    .map((f) => {
      const rel = f.slice(pkg.dist.length + 1);
      return `// ── dist/${rel} ${"─".repeat(Math.max(0, 60 - rel.length))}\n${normalise(readFileSync(f, "utf8"))}\n`;
    })
    .join("\n");
  const target = join(ROOT, "api-surface", `${pkg.name}.d.ts`);
  writeFileSync(target, `${header}\n${body}\n`);
  console.log(
    `[api-surface] wrote api-surface/${pkg.name}.d.ts (${files.length} declaration files)`,
  );
}

if (mode === "check") {
  console.log("[api-surface] checking for drift…");
  const diff = spawnSync("git", ["diff", "--exit-code", "--", "api-surface/"], {
    stdio: "inherit",
    cwd: ROOT,
  });
  if (diff.status !== 0) {
    console.error(
      "\n[api-surface] PUBLIC API SURFACE DRIFTED. If intentional, run `pnpm api:generate` and commit api-surface/.",
    );
    process.exit(1);
  }
  console.log("[api-surface] no drift — public type surface matches committed snapshot.");
}
